version: '2.1'

services:

  elevators_nginx:
    image: nginx:stable
    networks:
      - elevators_network
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elevators_phpfpm

  elevators_phpfpm:
    build:
      context: ./docker/phpfpm
    networks:
      - elevators_network
    volumes:
      - ./:/var/www/elevators
    working_dir: /var/www/elevators

  elevators_composer:
    image: composer

networks:
  elevators_network:
    driver: bridge